name: Deploy to GitHub Pages

on:
  push:
    branches:
      - dev  # 设置要部署的分支，根据你的默认分支可能是master或main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js 🔧
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies 📦
        run: npm ci

      - name: Build 🏗️
        run: npm run build

      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist  # 构建输出目录
          branch: dev  # 部署分支
